spring.datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: admin
  driver-class-name: org.postgresql.Driver
  hikari:
    pool-name: springHikariCP
    maximum-pool-size: 10
    minimum-idle: 5
    connection-timeout: 30000
    max-lifetime: 1800000
